### ISSUE TITLE
Validate vSphere user name and password does not contain a backslash

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere#3992]
Validate the vSphere EKSA_VSPHERE_USERNAME and EKSA_VSPHERE_PASSORD does not contain a backslash. Ideally, we'd base64 encode this, but maybe it is a capv problem.

Work around, use username@domain instead of domain\username

**Comment by TerryHowe** [comment]
Is this just broken for username now? https://github.com/aws/eks-anywhere/pull/1677 maybe it is fixed?

**Comment by vivek-koppuru** [comment]
I think we need to do the same thing we did in the above PR here:

https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/template-cp.yaml#L548-L549

**Comment by vivek-koppuru** [comment]
Either we need to do the above, or add a validation not allowing the specification of a user as `domain_name/user_name`. I would lean towards enabling both configurations as govc supports it as well.

**Comment by raykrueger** [comment]
This is still an issue as of 0.13.0 If someone uses the user\domain format in their EKA_VSPHERE_USERNAME they will get the following obtuse error message.

```Error: applying capi spec: executing apply: error: error parsing STDIN: error converting YAML to JSON: yaml: line 9: found unknown escape character```

**Comment by chrisdoherty4** [comment]
Did we establish what the vSphere constraints are? As Terry said in the OP, we really shouldn't block this, particularly for passwords.
